- name: Provision instances
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    slaves: 1
  tasks:
    - name: Provision master
      ec2:
        key_name: ansibleqa
        group: ansibleqa
        instance_type: m3.large
        image: ami-d05e75b8
        region: us-east-1
        vpc_subnet_id: subnet-fc39df8b
        # assign_public_ip: yes
        wait: true
        exact_count: 1
        count_tag:
          Name: jmmaster
        instance_tags:
          Name: jmmaster
      register: jmm

    - name: Provision slaves
      ec2:
        key_name: ansibleqa
        group: ansibleqa
        instance_type: m3.medium
        image: ami-d05e75b8
        region: us-east-1
        vpc_subnet_id: subnet-fc39df8b
        # assign_public_ip: yes
        wait: true
        exact_count: "{{slaves}}"
        count_tag:
          Name: jmslave
        instance_tags:
          Name: jmslave
      register: jms

    - name: Add master server to appropriate groups
      add_host: hostname={{ item.private_ip }} groups=jmqamaster
      # add_host: hostname={{ item.private_ip }} groups=jmeter
      with_items: jmm.instances

    - name: Wipe ids file
      file:
        dest: ./instanceids
        state: absent

    - name: Write master instance to file
      lineinfile:
        create: yes
        dest: ./instanceids
        line: "{{ item.id }}"
      with_items: jmm.instances

    - name: Write slaves
      lineinfile:
        create: yes
        dest: ./instanceids
        line: "{{ item.id }}"
      with_items: jms.instances

    - name: Add slave servers to appropriate groups
      add_host: hostname={{ item.private_ip }} groups=jmqaslaves
      # add_host: hostname={{ item.private_ip }} groups=jmeter
      with_items: jms.instances

    - name: Wait for ssh
      wait_for: host={{ item.private_ip }} port=22 timeout=600 state=started
      with_items: jms.instances

    - name: Wait for key to be added to ssh interface
      pause: seconds=30



- hosts: jmqamaster:jmqaslaves
  gather_facts: false
  name: Configuration pass
  user: ubuntu
  sudo: yes
  gather_facts: false
  tasks:
    - name: turn off firewall
      ufw: state=disabled
    - name: Update cache
      apt: update_cache=yes
    - name: Install java
      apt: name=default-jdk
    - name: Install Unzip
      apt: name=unzip
    - name: Download standard plugins
      get_url:
        url: http://jmeter-plugins.org/downloads/file/JMeterPlugins-Standard-1.3.0.zip
        dest: ~/
    - name: Download extras
      get_url:
        url: http://jmeter-plugins.org/downloads/file/JMeterPlugins-Extras-1.3.0.zip
        dest: ~/
    - name: Download jmeter
      get_url:
        url: http://archive.apache.org/dist/jmeter/binaries/apache-jmeter-2.9.zip
        dest: ~/
    - name: Unzip jmeter
      unarchive:
        copy: no
        src: /root/apache-jmeter-2.9.zip
        dest: /home/ubuntu
    - name: Wait for zip
      wait_for:
        path: /home/ubuntu/apache-jmeter-2.9
        state: present
    - name: Unzip plugins
      unarchive:
        copy: no
        src: /root/JMeterPlugins-Standard-1.3.0.zip
        dest: /home/ubuntu/apache-jmeter-2.9
      unarchive:
        copy: no
        src: /root/JMeterPlugins-Extras-1.3.0.zip
        dest: /home/ubuntu/apache-jmeter-2.9
    - name: Change owner
      file:
        path: /home/ubuntu
        recurse: yes
        owner: ubuntu
        group: sudo
        mode: 0755


- name: Start jmeter server
  # gather_facts: false
  hosts: jmqaslaves
  user: ubuntu
  sudo: yes
  tasks:
  - name: Run command
    shell: nohup /home/ubuntu/apache-jmeter-2.9/bin/jmeter-server -Djava.rmi.server.hostname={{ ansible_eth0.ipv4.address }} &

- name: create host list
  gather_facts: false
  hosts: localhost
  connection: local
  tasks:
  - debug: msg="{{ item.private_ip }}"
    with_items: jms.instances
    register: output
    always_run: True
    changed_when: False
    run_once: True
    # delegate_to: jmqamaster
  # - set_fact: ips={{ output.results|map(attribute='msg')|join(',') }}

- name: Set master server
  gather_facts: false
  hosts: jmqamaster
  user: ubuntu
  sudo: yes
  gather_facts: false
  tasks:
    - name: Push jmx file
      copy:
        src: "./{{ jmx_file }}"
        dest: ~/
    - name: Move file
      command: "mv ~/{{ jmx_file }} /home/ubuntu"

- name: Run test
  gather_facts: false
  hosts: jmqamaster
  user: ubuntu
  tasks:
    - name: Run jmx file against remote servers
      shell: /home/ubuntu/apache-jmeter-2.9/bin/jmeter -n -t ~/{{ jmx_file }} -R{{ hostvars.localhost.output.results|map(attribute='msg')|join(',') }}
    - name: Retrieve results
      fetch:
        src: "{{ results }}"
        dest: ./results
    - name: Retrieve log
      fetch:
        src: jmeter.log
        dest: ./results

- name: Terminate instances
  hosts: localhost
  connection: local
  tasks:
    - name: terminate instance
      ec2: state=absent instance_ids={{item.id}} key_name=ansibleqa region=us-east-1
      with_items: jms.instances
      ec2: state=absent instance_ids={{item.id}} key_name=ansibleqa region=us-east-1
      with_items: jmm.instances
